### ISSUE TITLE
Windows 环境下缺少 icudtl.dat 文件导致 SkIcuLoader 模块加载失败

### ISSUE THREAD

**Issue by blyc** [BalconyJH/DynRender-skia#22]
环境： python3.9 
动态id为：`975103398984548358`
代码为项目示例
```
import httpx
import asyncio
import skia
from dynrender_skia.Core import DynRender
from dynamicadaptor.DynamicConversion import formate_message


# 现在风控升级，大概率请求失败，建议携带cookie进行请求
async def web_test():
    dyn_id = "975103398984548358"
    url = f"https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?timezone_offset=-480&id={dyn_id}&features=itemOpusStyle"
    headers = {
        "referer": f"https://t.bilibili.com/{dyn_id}",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0"
    }

    # 发起HTTP请求并解析JSON响应
    message_json = httpx.get(url, headers=headers).json()
    print(message_json)
    # 格式化消息数据
    message_formate = await formate_message("web", message_json["data"]["item"])

    # 使用DynRender执行动态渲染
    img = await DynRender().run(message_formate)

    # 将渲染后的图像转换为Skia Image对象
    img = skia.Image.fromarray(img, colorType=skia.ColorType.kRGBA_8888_ColorType)

    # 保存图像为PNG文件
    img.save("1.png")


# 当文件作为主程序执行时
if __name__ == "__main__":
    asyncio.run(web_test())


```

运行结果：
···
SkIcuLoader: datafile missing: D:\miniconda3\envs\tempprj\icudtl.dat.
SkIcuLoader: datafile missing: D:\miniconda3\envs\tempprj\lib\site-packages\icudtl.dat.

进程已结束，退出代码为 -1073741819 (0xC0000005)
···

**Comment by blyc** [comment]
当前的piplist
```
Package           Version
----------------- ---------
aiofiles          23.2.1
annotated-types   0.7.0
anyio             4.6.0
certifi           2024.8.30
colorama          0.4.6
DynamicAdaptor    0.5.5
dynrender_skia    0.2.8
emoji             2.13.2
exceptiongroup    1.2.2
h11               0.14.0
httpcore          1.0.5
httpx             0.27.2
idna              3.10
loguru            0.6.0
numpy             2.0.2
pip               24.2
pybind11          2.13.6
pydantic          2.9.2
pydantic_core     2.23.4
setuptools        75.1.0
skia-python       126.0b8
sniffio           1.3.1
tenacity          9.0.0
typing_extensions 4.12.2
wheel             0.44.0
win32-setctime    1.1.0
```

**Comment by Polyisoprene** [comment]
请提供以下信息：
运行平台及系统版本：
python版本：
使用的IDE及版本：

**Comment by blyc** [comment]
> 请提供以下信息： 运行平台及系统版本： python版本： 使用的IDE及版本：

运行平台及系统版本： win10专业版 22h2       （另有发布在   window server 2012 R2 datacenter  同样问题
python版本： 3.9.19     （miniconda环境）
使用的IDE及版本：jetbrain pycharm 2024.2.1

**Comment by BalconyJH** [comment]
感谢你的反馈以及详细描述。

我们发现该 SkIcuLoader 回报的 datafile missing 为 Skia 对 ICU 数据的依赖，而不是本项目内的静态文件缺失。正如上游的 [skia-python issue #268](https://github.com/kyamagu/skia-python/issues/268) 中所提到的，临时解决办法是手动将缺失的 `icudtl.dat` 文件放到 Python 环境里。而且我们均未成功复现这个问题，因此难以提供更多帮助。

该问题属于上游依赖项的范畴，我们会将该 issue 标记为 `wontfix` 并关闭，建议直接参考上游的解决方案。

**Comment by blyc** [comment]
感谢两位的回复~

在我将 `icudtl.dat` 移入指定文件夹后成功消除了 `SkIcuLoader` 的警告
而实际上我的疑问 `进程已结束，退出代码为 -1073741819 (0xC0000005)` 的异常崩溃也没有再出现 （_很抱歉我最开始描述稍稍引起了一些误导_）

而后我重启了电脑并将 `icudtl.dat` 从项目移除后，虽然 `SkIcuLoader` 的警告再次出现，但并没有出现异常崩溃且成功渲染出了动态图片 （_奇怪的重启大法_），目前异常崩溃的最大原因怀疑为本机的环境异常，待后续再有崩溃我再着重检查本机环境。

再次感谢回复和帮助。

**Comment by HinTak** [comment]
The warning is associated with skUnicode so is only relevant in you use text related functionality.

**Comment by BalconyJH** [comment]
> The warning is associated with skUnicode so is only relevant in you use text related functionality.

Thanks for the clarification! Since our project uses text-related functionality for rich text rendering, this warning is pretty much expected. We appreciate your contri and will keep an eye on any upstream updates or solutions👀
